### ISSUE TITLE
New featrues for cross-user file sharing

### ISSUE THREAD

**Issue by milkice233** [linesoft2/open2share#4]
Hello!

I found your project quite fascinating and I really like this idea. But it seems that open2share currently doesn't support cross-user file sharing. In my sceanrio, I've installed QQ and open2share in work profile via [Island](https://github.com/oasisfeng/island) . When I open the file with open2share, I can't find an share option to "switch to mainland" like many other app does. So I'm wondering if this is a technical limitation or just not being implemented. Thanks!

作者你好，

我发现 open2share 什么都挺好就是似乎不支持跨用户文件分享，我用 Island 创建的工作目录并且把 QQ 和 open2share 安装到 Island 里去，然后在 Island 里的 QQ 上用 open2share 打开之后在分享菜单里没有“切换至个人空间”这样的一个选项（这个选项可以允许跨用户分享文件，在我的场景下就是从 Island 里用 open2share 把 QQ 上下载到的文件分享到主用户空间的 App 里去），比较好奇是技术限制还是单纯没有实现，谢谢

**Comment by linesoft2** [comment]
工作空间和原有的空间是完全独立的吧？貌似并不能实现。
你用其他软件进行分享的时候有“切换至个人空间”这个选项吗？

**Comment by milkice233** [comment]
当然有 不然我不会提出来的
但是前两天我升级到了 Android 11 之后，系统的分享菜单里可以切换至主用户目录，所以感觉可能是 Android 10 及以下的问题

**Comment by Sodium-Aluminate** [comment]
> 工作空间和原有的空间是完全独立的吧？貌似并不能实现。 你用其他软件进行分享的时候有“切换至个人空间”这个选项吗？

工作空间有合适的“转发到个人空间”的办法（但我忘记了…）

~~另外工作空间想逃逸到另一个空间还是有很多脏方法的，比如 obb 文件夹（迅雷之前就滥用这个文件夹），或者借助监听本地端口~~
