### ISSUE TITLE
Inclusion in F-droid

### ISSUE THREAD

**Issue by proletarius101** [linesoft2/open2share#5]
Hi, I'm sending a PR to include this app to F-droid: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8036

Would you agree?

**Comment by IzzySoft** [comment]
F-Droid maintainer here. We'd like to comply to the inclusion request, but there are still open questions we need answers to from you:

* what for does your app require `INTERNET` permission? That's not clear from the description.
* it's also not entirely clear (to me at least) where one opens what file so your app processes it: from file managers? Or from apps not supporting to share their contents, but having a "save to" option?
* we'd much prefer summary, description and ideally also screenshots being available from your repo here (using [Fastlane structures](https://gitlab.com/snippets/1895688)) so you can maintain them yourself whenever you feel like. We'd help you setting this up if you want.

So currently, the inclusion process is stuck, waiting for your response. Would you please help out? Thanks in advance!

**Comment by linesoft2** [comment]
Yes, I agree. Thank you for submitting my software to the F-Droid

**Comment by linesoft2** [comment]
> F-Droid maintainer here. We'd like to comply to the inclusion request, but there are still open questions we need answers to from you:
> 
> * what for does your app require `INTERNET` permission? That's not clear from the description.
> * it's also not entirely clear (to me at least) where one opens what file so your app processes it: from file managers? Or from apps not supporting to share their contents, but having a "save to" option?
> * we'd much prefer summary, description and ideally also screenshots being available from your repo here (using [Fastlane structures](https://gitlab.com/snippets/1895688)) so you can maintain them yourself whenever you feel like. We'd help you setting this up if you want.
> 
> So currently, the inclusion process is stuck, waiting for your response. Would you please help out? Thanks in advance!

1.The `INTERNET` permission is requested for the GuideActivity. Here is a WebView to display the related guides.
2.From apps not supporting to share their contents, then open the system's share menu. This is very helpful for many Chinese applications, such as wechat and QQ.
3.I will create a Fastlane structures.
Thank you for your inclusion.

**Comment by proletarius101** [comment]
Thanks! And please see the follow-ups here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8036#note_523851590. Summary: you'd better make it static (or just create an Activity for that), rather than introducing the Internet permission, which is dangerous and not related to the main functionality. And it can be altered arbitrarily out of your intention.

**Comment by linesoft2** [comment]
> Thanks! And please see the follow-ups here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8036#note_523851590. Summary: you'd better make it static (or just create an Activity for that), rather than introducing the Internet permission, which is dangerous and not related to the main functionality.

OK, thank you for advice.

**Comment by IzzySoft** [comment]
Thanks for picking this up, @linesoft2 – and for actively supporting the inclusion! Please let us know once Fastlane is available (I gladly assist checking it's fine). And please consider including above details with the app description (aka `full_description.txt`). If you need help with that, just ask :smiley:

**Comment by IzzySoft** [comment]
As the question just came up again: can you confirm you will implement the discussed changes (i.e. Fastlane and removing the `INTERNET` permission), @linesoft2?
