### ISSUE TITLE
使用钉钉分享PDF文件会崩溃

### ISSUE THREAD

**Issue by Haili28156** [linesoft2/open2share#8]
![Screenshot_2022-09-05-15-52-30-528_com.alibaba.android.rimet-edit.jpg](https://user-images.githubusercontent.com/79240109/188397352-876084ff-3ddf-40b7-9364-44612b4d46e2.jpg)
Android12
MIUI13
open2share 1.6

**Comment by lz233** [comment]
点击查看日志摘要并截图

**Comment by Haili28156** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{top.linesoft.open2share/top.linesoft.open2share.ReceiveOpenActivity}: android.os.FileUriExposedException: file:///storage/emulated/0/DingTalk/904%E4%BD%9C%E4%B8%9A9.5.pdf exposed beyond app through ClipData.Item.getUri()      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3769)      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3943)      at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:106)      at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291)      at android.os.Handler.dispatchMessage(Handler.java:106)      at android.os.Looper.loopOnce(Looper.java:211)      at android.os.Looper.loop(Looper.java:300)      at android.app.ActivityThread.main(ActivityThread.java:8314)      at java.lang.reflect.Method.invoke(Native Method)      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)Caused by: android.os.FileUriExposedException: file:///storage/emulated/0/DingTalk/904%E4%BD%9C%E4%B8%9A9.5.pdf exposed beyond app through ClipData.Item.getUri()      at android.os.StrictMode.onFileUriExposed(StrictMode.java:2209)      at android.net.Uri.checkFileUriExposed(Uri.java:2402)      at android.content.ClipData.prepareToLeaveProcess(ClipData.java:1052)      at android.content.Intent.prepareToLeaveProcess(Intent.java:11400)      at android.content.Intent.prepareToLeaveProcess(Intent.java:11406)      at android.content.Intent.prepareToLeaveProcess(Intent.java:11385)      at android.app.Instrumentation.execStartActivity(Instrumentation.java:1759)      at android.app.Activity.startActivityForResult(Activity.java:5507)      at androidx.activity.ComponentActivity.startActivityForResult(Unknown Source:0)      at android.app.Activity.startActivityForResult(Activity.java:5465)      at androidx.activity.ComponentActivity.startActivityForResult(Unknown Source:0)      at top.linesoft.open2share.ReceiveOpenActivity.onCreate(Unknown Source:54)      at android.app.Activity.performCreate(Activity.java:8192)      at android.app.Activity.performCreate(Activity.java:8159)      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1342)      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3749)      ... 12 more获取Outlook for Android

**Comment by guxin0123** [comment]
同bug
钉钉  分享xlsx
Android 13
miui 14 
open2share 1.5

**Comment by linesoft2** [comment]
应该是钉钉把文件的原始 uri 暴露了被 Android 阻止了，Android 已不允许这种做法，下个版本会考虑增加一个选项以允许这种行为。

**Comment by ryanfys** [comment]
碰到了同bug
希望开发者能够修复！

**Comment by yan1990y** [comment]
> 应该是钉钉把文件的原始 uri 暴露了被 Android 阻止了，Android 已不允许这种做法，下个版本会考虑增加一个选项以允许这种行为。

同bug，大佬有更新吗
